fix: change the way to check the download status

diff --git a/.github/workflows/commitNewDataFile.yml b/.github/workflows/commitNewDataFile.yml
--- a/.github/workflows/commitNewDataFile.yml
+++ b/.github/workflows/commitNewDataFile.yml
@@ -9,35 +9,36 @@ on:
 #     - cron: "*/10 * * * *"
 
 jobs:
-  downloadDataFile:
+  dateUpdate:
     runs-on: ubuntu-latest
     steps:
+    - name: Install Node.js dependencies
+      run: npm install
+
     - name: Download the new data file
-      id: dataUpdate
-      uses: cindyli/data-update-action@main
+      id: downloadFile
+      run: |
+        npm run update
+        echo ::set-output name=status::$?
 
-    - name: Get the output status
-      run: echo "The update status was ${{ steps.dataUpdate.outputs.new-data-file }}"
+    - name: Set push config
+      if: steps.downloadFile.outputs.status == 0
+      uses: actions/checkout@master
+      with:
+        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
 
-  # push:
-  #   runs-on: ubuntu-latest
-  #   needs: downloadDataFile
-  #   if: needs.downloadDataFile.outputs.new-data-file != "none"
-  #   steps:
-  #   - uses: actions/checkout@master
-  #     with:
-  #       persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
-  #       fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
-  #
-  #   - name: Commit the new data file and the updated latest.json
-  #     run: |
-  #       git config --local user.email "wecount.info@gmail.com"
-  #       git config --local user.name "Auto Update via GitHub Action"
-  #       git add ODC/*
-  #       git commit -m "feat: add a published new data file from https://data.ontario.ca" -a
-  #
-  #   - name: Push changes
-  #     uses: ad-m/github-push-action@master
-  #     with:
-  #       github_token: ${{ secrets.GITHUB_TOKEN }}
-  #       branch: ${{ github.ref }}
+    - name: Commit the new data file and the updated latest.json
+      if: steps.downloadFile.outputs.status == 0
+      run: |
+        git config --local user.email "wecount.info@gmail.com"
+        git config --local user.name "Auto Update via GitHub Action"
+        git add ODC/*
+        git commit -m "feat: add a published new data file from https://data.ontario.ca" -a
+
+    - name: Push changes
+      if: steps.downloadFile.outputs.status == 0
+      uses: ad-m/github-push-action@master
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        branch: ${{ github.ref }}
